# Generated by Django 5.0.3 on 2025-12-22 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kategori_utama', models.CharField(choices=[('ARMADA', 'Biaya Armada (Bensin, Servis, Tol, Supir)'), ('KANTOR', 'Biaya Kantor (Listrik, WiFi, ATK, Gaji Admin)'), ('LAINNYA', 'Biaya Lain-lain (Sumbangan, Tak Terduga)')], max_length=20, verbose_name='Kategori Pengeluaran')),
                ('deskripsi', models.CharField(help_text='Contoh: Bensin Truk H-1234-AB', max_length=255, verbose_name='Keterangan Detail')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (Rp)')),
                ('bukti_foto', models.ImageField(blank=True, null=True, upload_to='keuangan/bukti/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Biaya Operasional',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Invoice')),
                ('issue_date', models.DateField(verbose_name='Tanggal Terbit')),
                ('due_date', models.DateField(verbose_name='Jatuh Tempo')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Tagihan (Rp)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sudah Dibayar (Rp)')),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Lunas'), ('PARTIAL', 'Cicilan Sebagian'), ('PAID', 'Lunas')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='gudang.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Bayar')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Bayar (Rp)')),
                ('method', models.CharField(default='Transfer Bank', max_length=50, verbose_name='Metode')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='keuangan/payment/', verbose_name='Bukti Transfer')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='keuangan.invoice')),
            ],
        ),
    ]
