# Generated by Django 5.0 on 2025-12-17 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gudang', '0002_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('BENSIN', 'Bahan Bakar (BBM)'), ('MAKAN', 'Uang Makan Supir'), ('TOL', 'Biaya Tol / Parkir'), ('SERVIS', 'Servis & Sparepart (Maintenance)'), ('LAIN', 'Lain-lain')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Biaya (Rp)')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, verbose_name='Detail (Nama Bengkel/Ket)')),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to='operasional/', verbose_name='Foto Nota/Struk')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Di-ACC Owner?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('armada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_costs', to='core.armada')),
            ],
            options={
                'verbose_name_plural': 'Biaya Operasional',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='No Invoice')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Tagihan (Rp)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sudah Dibayar (Rp)')),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sisa Hutang (Rp)')),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Lunas (Merah)'), ('PARTIAL', 'Cicilan (Kuning)'), ('PAID', 'Lunas (Hijau)')], default='UNPAID', max_length=10, verbose_name='Status Pembayaran')),
                ('due_date', models.DateField(verbose_name='Jatuh Tempo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='gudang.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nominal Bayar (Rp)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Bayar')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Bukti Transfer')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='keuangan.invoice')),
            ],
        ),
    ]
