# Generated by Django 5.0 on 2025-12-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biayaoperasional',
            options={},
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='foto_bukti',
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='biayaoperasional',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='bukti_foto',
            field=models.ImageField(blank=True, null=True, upload_to='biaya_ops/'),
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='description',
            field=models.TextField(default='-', verbose_name='Deskripsi Masalah/Keterangan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='jenis_biaya',
            field=models.CharField(choices=[('PERBAIKAN', 'Perbaikan / Service'), ('ONGKOS', 'Ongkos Jalan / BBM'), ('RUTIN', 'Rutin (Gaji/Listrik)'), ('DADAKAN', 'Dadakan (Sumbangan/Lainnya)')], default='-', max_length=20, verbose_name='Jenis Biaya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='kategori_utama',
            field=models.CharField(choices=[('ARMADA', 'Biaya Armada'), ('KANTOR', 'Biaya Kantor')], default='KANTOR', max_length=10),
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='status',
            field=models.CharField(choices=[('PROSES', 'Dalam Proses'), ('SELESAI', 'Selesai')], default='SELESAI', max_length=10),
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Tgl Selesai'),
        ),
        migrations.AddField(
            model_name='biayaoperasional',
            name='urgensi',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'URGENT')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='biayaoperasional',
            name='armada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.armada'),
        ),
        migrations.AlterField(
            model_name='biayaoperasional',
            name='nominal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='biayaoperasional',
            name='tanggal',
            field=models.DateField(verbose_name='Tgl Laporan'),
        ),
    ]
