# Generated by Django 5.0 on 2025-12-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_email'),
        ('keuangan', '0003_add_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biayaoperasional',
            name='armada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_list', to='core.armada', verbose_name='Pilih Armada (Jika ada)'),
        ),
        migrations.AlterField(
            model_name='biayaoperasional',
            name='deskripsi',
            field=models.TextField(max_length=255, verbose_name='Keterangan Detail'),
        ),
    ]
