# Generated by Django 5.0.3 on 2026-01-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kabupaten_alter_fertilizerprice_price_buy_and_more'),
        ('keuangan', '0004_alter_biayaoperasional_armada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayaoperasional',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_list', to='core.kabupaten'),
        ),
    ]
