# Generated by Django 5.0 on 2025-12-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Plat Nomor')),
                ('vehicle_type', models.CharField(help_text='Contoh: Truk Engkel, Pickup L300', max_length=50, verbose_name='Jenis Kendaraan')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Nama Supir')),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Foto Kendaraan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif?')),
            ],
            options={
                'verbose_name_plural': 'Data Armada',
            },
        ),
        migrations.CreateModel(
            name='FertilizerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_type', models.CharField(choices=[('NPK', 'NPK (Merah)'), ('UREA', 'UREA (Biru)')], max_length=10, unique=True, verbose_name='Jenis Pupuk')),
                ('price_buy', models.DecimalField(decimal_places=2, help_text='Harga beli dari Holding', max_digits=15, verbose_name='Harga Tebus (Beli)')),
                ('price_sell', models.DecimalField(decimal_places=2, help_text='Harga jual ke Kios', max_digits=15, verbose_name='Harga Jual (Distribusi)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Master Harga Pupuk',
            },
        ),
        migrations.CreateModel(
            name='Kios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kios')),
                ('pic_name', models.CharField(max_length=100, verbose_name='Nama Penanggung Jawab')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('district', models.CharField(help_text='Kecamatan sangat penting untuk fitur Fluid Allocation', max_length=50, verbose_name='Kecamatan')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor HP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kios',
            },
        ),
        migrations.CreateModel(
            name='KiosAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, verbose_name='Tahun Anggaran')),
                ('fertilizer_type', models.CharField(choices=[('NPK', 'NPK (Merah)'), ('UREA', 'UREA (Biru)')], max_length=10, verbose_name='Jenis Pupuk')),
                ('quota_original', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jatah Awal (Ton)')),
                ('quota_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sisa Kuota (Ton)')),
                ('kios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.kios')),
            ],
            options={
                'verbose_name_plural': 'Alokasi Kuota Kios',
                'unique_together': {('kios', 'year', 'fertilizer_type')},
            },
        ),
    ]
