# Generated by Django 5.0 on 2025-12-22 21:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Plat Nomor')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Jenis Kendaraan')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Nama Supir')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='armada/', verbose_name='Foto Kendaraan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif?')),
            ],
            options={
                'verbose_name_plural': 'Data Armada',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CV. BERKAH TANI', max_length=100, verbose_name='Nama Perusahaan')),
                ('address', models.TextField(default='Jl. Raya Salatiga - Semarang KM 5', verbose_name='Alamat Kantor')),
                ('phone', models.CharField(default='0812-3456-7890', max_length=50, verbose_name='No. Telepon/WA')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo Perusahaan')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='Nama Bank')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='No. Rekening')),
            ],
            options={
                'verbose_name': 'Profil Perusahaan',
                'verbose_name_plural': 'Profil Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='JenisPupuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Pupuk')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Singkatan')),
                ('color', models.CharField(default='primary', help_text='primary, success, danger, warning, atau kode Hex', max_length=20, verbose_name='Warna Label (Bootstrap/Hex)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Master Jenis Pupuk',
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kecamatan')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Wilayah')),
                ('target_tonnage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Target Tahunan (Ton)')),
            ],
            options={
                'verbose_name_plural': 'Master Kecamatan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Tebus (Per KG)')),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Jual (Per KG)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_pupuk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_config', to='core.jenispupuk', verbose_name='Jenis Pupuk')),
            ],
            options={
                'verbose_name_plural': 'Master Harga Pupuk',
            },
        ),
        migrations.CreateModel(
            name='Kios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kios')),
                ('pic_name', models.CharField(max_length=100, verbose_name='Nama Penanggung Jawab')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('phone', models.CharField(max_length=20, verbose_name='Nomor HP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kios_list', to='core.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Data Kios',
            },
        ),
        migrations.CreateModel(
            name='KiosAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, verbose_name='Tahun Anggaran')),
                ('quota_original', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Jatah Awal (Ton)')),
                ('quota_remaining', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Sisa Kuota (Ton)')),
                ('jenis_pupuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenispupuk', verbose_name='Jenis Pupuk')),
                ('kios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.kios')),
            ],
            options={
                'verbose_name_plural': 'Alokasi Kuota Kios',
                'unique_together': {('kios', 'year', 'jenis_pupuk')},
            },
        ),
    ]
