# Generated by ChatGPT on 2025-12-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
