# Generated by Django 5.0 on 2026-01-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kabupaten')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Kabupaten',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='fertilizerprice',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Tebus (Per Ton)'),
        ),
        migrations.AlterField(
            model_name='fertilizerprice',
            name='price_sell',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Jual (Per Ton)'),
        ),
        migrations.AlterField(
            model_name='kiosallocation',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Tahun Anggaran'),
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kecamatan_list', to='core.kabupaten'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.kabupaten')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
