# Generated by Django 5.0 on 2026-02-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fertilizerprice_kabupaten_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenispupuk',
            name='color',
        ),
    ]
