# Generated by Django 5.0 on 2026-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jenispupuk_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atas Nama Rekening'),
        ),
    ]
