# Generated by Django 5.0 on 2026-02-06 17:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_bank_account_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kiosallocation',
            constraint=models.CheckConstraint(check=models.Q(('quota_remaining__gte', Decimal('0'))), name='quota_remaining_non_negative'),
        ),
    ]
