# Generated by Django 5.0 on 2026-02-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_quota_non_negative_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='kabupaten',
            field=models.OneToOneField(blank=True, help_text='Kosongkan untuk profil default. Isi untuk profil spesifik kabupaten.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='core.kabupaten'),
        ),
    ]
