"""
Django settings for sim_dp project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables dari file .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY CONFIGURATION (Risk R-01 & R-04) ---
# 1. SECRET_KEY: Wajib ada. Jika tidak, aplikasi akan stop (Fail Fast).
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable must be set and non-empty.")

# 2. DEBUG: Default False untuk keamanan
DEBUG = os.getenv('DEBUG', 'false').lower() in ('true', '1', 'yes')

# 3. ALLOWED_HOSTS: Wajib ada saat Production
_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if _hosts_env:
    # Split string berdasarkan koma dan bersihkan spasi
    ALLOWED_HOSTS = [h.strip() for h in _hosts_env.split(',') if h.strip()]
else:
    if not DEBUG:
        # Error jika di Production tapi lupa setting domain
        raise RuntimeError(
            "ALLOWED_HOSTS environment variable must be set when DEBUG=False. "
            "Please configure ALLOWED_HOSTS for your deployment."
        )
    # Jika di Local (DEBUG=True), biarkan kosong (Django otomatis izinkan localhost)
    ALLOWED_HOSTS = []

# 4. CSRF_TRUSTED_ORIGINS: Wajib untuk HTTPS/Coolify
_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _origins_env:
    CSRF_TRUSTED_ORIGINS = [url.strip() for url in _origins_env.split(',') if url.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Local Apps
    'core',  
    'gudang',
    'keuangan',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Untuk Static Files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Risk R-01 Anti-CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sim_dp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Folder template global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.access_controls', # Custom context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'sim_dp.wsgi.application'

# --- DATABASE CONFIGURATION (PostgreSQL - Risk R-05 Atomic) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Internationalization
LANGUAGE_CODE = 'id' # Set Bahasa Indonesia
TIME_ZONE = 'Asia/Jakarta' # Set Waktu WIB (Penting untuk Jatuh Tempo)
USE_I18N = True
USE_TZ = True

# Cookie security (should be True in production; configurable via env)
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')

# Konfigurasi Static Files (CSS, JS)
STATIC_URL = 'static/'
# Folder tempat mengumpulkan static files saat deploy
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Folder tempat kita menaruh CSS custom (yang sudah ada)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Aktifkan kompresi dan caching otomatis Whitenoise
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- KONFIGURASI PENYIMPANAN FILE (Cloudflare R2 vs Local) ---

# Cek apakah variabel R2_ACCESS_KEY_ID sudah disetting di Coolify
if os.getenv('R2_ACCESS_KEY_ID'):
    # === PRODUCTION (Cloudflare R2) ===
    # Otomatis dipakai saat website berjalan di Coolify
    
    # 1. Kredensial dari Environment Variables Coolify
    AWS_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('R2_ENDPOINT_URL')

    # 2. Konfigurasi agar kompatibel dengan R2
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400', # Cache gambar 1 hari agar cepat
    }
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_REGION_NAME = 'auto'  # R2 set auto
    AWS_S3_FILE_OVERWRITE = False # Jangan timpa file jika nama sama
    
    # 3. Gunakan library django-storages
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media", # Simpan di folder /media di Cloudflare
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # 4. URL Public untuk akses gambar
    # Ini akan menggunakan URL Public R2 yang nanti Anda setting di Cloudflare
    # Format: https://pub-<kode>.r2.dev/media/
    # Jika belum diset, kode ini akan mencoba menebak (tapi sebaiknya diset di .env jika punya custom domain)
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/' 

else:
    # === DEVELOPMENT (Laptop / Localhost) ===
    # Dipakai saat Anda coding di laptop
    
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    # Gunakan penyimpanan hardisk laptop biasa
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
WHITENOISE_MANIFEST_STRICT = False

# Auth redirects
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'