# Generated by Django 5.0.3 on 2025-12-22 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(help_text='Nomor Sales Order dari Pabrik', max_length=50, unique=True, verbose_name='Nomor SO')),
                ('date', models.DateField(verbose_name='Tanggal Penebusan')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='documents/so/', verbose_name='Bukti DO/SO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Centang otomatis jika sisa stok virtual habis', verbose_name='Selesai?')),
                ('jenis_pupuk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jenispupuk', verbose_name='Jenis Pupuk')),
            ],
            options={
                'verbose_name': 'Data Penebusan (SO)',
                'verbose_name_plural': 'Data Penebusan (SO)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat_jalan', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Surat Jalan')),
                ('date', models.DateField(verbose_name='Tanggal Kirim')),
                ('pkp_date', models.DateField(help_text='Tanggal administrasi perpajakan/laporan', verbose_name='Tanggal PKP')),
                ('source_type', models.CharField(choices=[('VIRTUAL', 'Langsung dari Pabrik (Potong SO)'), ('PHYSICAL', 'Dari Gudang Penyangga (Potong Stok Fisik)')], default='VIRTUAL', max_length=10, verbose_name='Sumber Stok')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Kirim (Ton)')),
                ('driver_name_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Nama Supir (Saat Kirim)')),
                ('nopol_snapshot', models.CharField(blank=True, max_length=20, verbose_name='Nopol (Saat Kirim)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('armada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.armada', verbose_name='Armada Pengirim')),
                ('jenis_pupuk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jenispupuk', verbose_name='Jenis Pupuk')),
                ('kios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kios', verbose_name='Kios Tujuan')),
                ('source_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='gudang.salesorder', verbose_name='Ambil dari SO')),
            ],
            options={
                'verbose_name': 'Distribusi / Surat Jalan',
                'verbose_name_plural': 'Distribusi / Surat Jalan',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah (Ton)')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kecamatan', verbose_name='Alokasi Kecamatan')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='gudang.salesorder')),
            ],
            options={
                'verbose_name': 'Rincian Alokasi SO',
                'verbose_name_plural': 'Rincian Alokasi SO',
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal Transaksi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_type', models.CharField(choices=[('VIRTUAL', 'Stok Virtual (SO)'), ('PHYSICAL', 'Stok Fisik (Gudang)')], max_length=10, verbose_name='Tipe Stok')),
                ('transaction_type', models.CharField(choices=[('IN_SO', 'Penebusan Baru (Virtual In)'), ('OUT_TRF', 'Ditarik ke Gudang (Virtual Out)'), ('IN_TRF', 'Masuk Gudang (Physical In)'), ('OUT_DIST_V', 'Distribusi Langsung (Virtual Out)'), ('OUT_DIST_P', 'Distribusi Gudang (Physical Out)'), ('ADJUST', 'Penyesuaian / Opname')], max_length=20, verbose_name='Jenis Transaksi')),
                ('reference_number', models.CharField(max_length=100, verbose_name='No. Ref (SO/SJ)')),
                ('description', models.CharField(max_length=255, verbose_name='Keterangan')),
                ('qty_in', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Masuk')),
                ('qty_out', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Keluar')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Akhir')),
                ('jenis_pupuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenispupuk')),
            ],
            options={
                'verbose_name': 'Kartu Stok (Ledger)',
                'verbose_name_plural': 'Kartu Stok (Ledger)',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Masuk Gudang')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Ditarik (Ton)')),
                ('reference_code', models.CharField(blank=True, help_text='Nomor referensi pengiriman dari pabrik ke gudang kita', max_length=50, verbose_name='No. Surat Jalan Pabrik')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_so', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='gudang.salesorder', verbose_name='Sumber SO')),
            ],
            options={
                'verbose_name': 'Stok Masuk Gudang (Fisik)',
                'verbose_name_plural': 'Stok Masuk Gudang (Fisik)',
            },
        ),
    ]
