# Generated by Django 5.0 on 2025-12-17 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_code', models.CharField(help_text='Awal 3101=NPK, 3820=UREA', max_length=50, unique=True, verbose_name='Kode SO')),
                ('fertilizer_type', models.CharField(choices=[('NPK', 'NPK (Merah)'), ('UREA', 'UREA (Biru)')], editable=False, max_length=10, verbose_name='Jenis Pupuk')),
                ('tonnage_initial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tonase Awal')),
                ('tonnage_current', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sisa Stok')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Penebusan')),
                ('maturity_date', models.DateField(editable=False, verbose_name='Jatuh Tempo Gudang')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Sudah Habis?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Data Penebusan (SO)',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_type', models.CharField(choices=[('IN', 'Masuk (Penebusan)'), ('OUT', 'Keluar (Penyaluran)')], max_length=5, verbose_name='Tipe Transaksi')),
                ('reference_number', models.CharField(help_text='No SO atau No Surat Jalan', max_length=100, verbose_name='Referensi')),
                ('qty_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mutasi (Ton)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Akhir (Ton)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_cards', to='gudang.salesorder')),
            ],
            options={
                'verbose_name_plural': 'Kartu Stok (Log)',
                'ordering': ['-date'],
            },
        ),
    ]
