# Generated by Django 5.0 on 2025-12-17 01:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage_sent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tonase Dikirim')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Kirim')),
                ('surat_jalan_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='No Surat Jalan')),
                ('notes', models.TextField(blank=True, help_text='Catatan khusus / Fluid Allocation', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('armada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='core.armada')),
                ('kios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='core.kios')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='gudang.salesorder', verbose_name='Sumber SO')),
            ],
            options={
                'verbose_name_plural': 'Data Penyaluran (Distribusi)',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
