# Generated by Django 5.0 on 2025-12-18 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_distribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Stok Sistem (Sebelum)')),
                ('actual_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stok Fisik (Actual)')),
                ('adjustment_qty', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Selisih (Adjustment)')),
                ('reason', models.TextField(help_text='Wajib diisi detail. Contoh: Stock Opname Bulan November 2025', verbose_name='Alasan Koreksi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Eksekutor')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='gudang.salesorder')),
            ],
            options={
                'verbose_name': 'Stock Opname / Adjustment',
                'ordering': ['-created_at'],
            },
        ),
    ]
