# Generated by GitHub Copilot (GPT-5.1-Codex-Max)
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0003_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='pkp_date',
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name='Tanggal PKP (Admin)',
                help_text='Tanggal yang tercetak di Surat Jalan & Invoice',
            ),
            preserve_default=False,
        ),
    ]
