# Generated by Django 5.0 on 2025-12-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gudang', '0004_add_pkp_date_to_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='district',
            field=models.CharField(choices=[('Bancak', 'Bancak'), ('Pabelan', 'Pabelan'), ('Suruh', 'Suruh'), ('Getasan', 'Getasan'), ('Tuntang', 'Tuntang')], default='Bancak', max_length=50, verbose_name='Alokasi Kecamatan'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='armada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.armada'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='kios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kios'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.salesorder'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='surat_jalan_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='tonnage_sent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tonase Kirim'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='transaction_date',
            field=models.DateField(verbose_name='Tanggal Ngirim (Fisik)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='entry_date',
            field=models.DateField(verbose_name='Tanggal Ngisi'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='fertilizer_type',
            field=models.CharField(choices=[('NPK', 'NPK'), ('UREA', 'UREA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='maturity_date',
            field=models.DateField(blank=True, verbose_name='Jatuh Tempo Gudang'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='so_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode SO (Batch)'),
        ),
    ]
