# Generated by Django 5.0 on 2025-12-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gudang', '0005_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='kios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.kios'),
        ),
    ]
