# Generated by Django 5.0 on 2026-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0009_distributionitem_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionitem',
            name='price_buy_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga beli per ton yang berlaku saat surat jalan dibuat.', max_digits=15, null=True, verbose_name='Harga Beli per Ton (saat transaksi)'),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='price_sell_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga jual per ton yang berlaku saat surat jalan dibuat.', max_digits=15, null=True, verbose_name='Harga Jual per Ton (saat transaksi)'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='transaction_type',
            field=models.CharField(choices=[('IN_SO', 'Penebusan Baru (Virtual In)'), ('OUT_TRF', 'Ditarik ke Gudang (Virtual Out)'), ('IN_TRF', 'Masuk Gudang (Physical In)'), ('IN_DIST_P', 'Distribusi Masuk Gudang (Physical In)'), ('OUT_DIST_V', 'Distribusi Langsung (Virtual Out)'), ('OUT_DIST_P', 'Distribusi Gudang (Physical Out)'), ('ADJUST', 'Penyesuaian / Opname')], max_length=20, verbose_name='Jenis Transaksi'),
        ),
    ]
