# Generated by Django 5.0 on 2026-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0011_backfill_price_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='source_type',
            field=models.CharField(choices=[('VIRTUAL', 'Langsung dari GPP (Potong SO)'), ('PHYSICAL', 'Gudang PUD (Potong Stok Fisik)')], default='VIRTUAL', max_length=10, verbose_name='Sumber Stok'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='source_type',
            field=models.CharField(choices=[('VIRTUAL', 'Langsung dari GPP (Potong SO)'), ('PHYSICAL', 'Gudang PUD (Potong Stok Fisik)')], default='VIRTUAL', max_length=10, verbose_name='Sumber Stok'),
        ),
        migrations.AlterField(
            model_name='stockcard',
            name='transaction_type',
            field=models.CharField(choices=[('IN_SO', 'Penebusan Baru (Virtual In)'), ('OUT_TRF', 'Pengisian Stok Fisik (Virtual Out)'), ('IN_TRF', 'Pengisian Stok Fisik (Physical In)'), ('IN_DIST_P', 'Pengisian Stok Fisik via Distribusi (Physical In)'), ('OUT_DIST_V', 'Distribusi Langsung (Virtual Out)'), ('OUT_DIST_P', 'Distribusi Gudang (Physical Out)'), ('ADJUST', 'Penyesuaian / Opname')], max_length=20, verbose_name='Jenis Transaksi'),
        ),
    ]
